# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hnc.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(QtWidgets.QMainWindow):
    def __init__(self, cc, tm, parent=None):
        super().__init__(parent)
        self.cc = cc
        self.setupUi(self)
        self.tm = tm
        self.connect_signals()

    def update_stlbl(self):
        if self.cc.poll():
            msg = self.cc.recv()
            self.statuslbl.setText(msg)

    def comm(self):
        self.cc.send("listen")

    def connect_signals(self):
        self.pushButton.clicked.connect(self.comm)
        self.tm.timeout.connect(self.update_stlbl)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(365, 403)
        MainWindow.setStyleSheet("background-color: rgb(53, 53, 53);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(110, 230, 150, 150))
        self.pushButton.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton.setStyleSheet("QPushButton {\n"
                                      "    color: rgb(39, 212, 111);\n"
                                      "    border: 2px solid #555;\n"
                                      "    border-radius: 75px;\n"
                                      "    border-style: outset;\n"
                                      "    background:rgb(58, 255, 81);\n"
                                      "    padding: 5px;\n"
                                      "    }\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background: rgb(63, 231, 74)\n"
                                      "    }\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    border-style: inset;\n"
                                      "    background:  rgb(53, 221, 64)\n"
                                      "    }")
        self.pushButton.setText("")
        self.pushButton.setIconSize(QtCore.QSize(40, 40))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(29, 30, 81, 31))
        self.label.setStyleSheet("font: 25 20pt \"Bahnschrift Light Condensed\";\n"
                                 "color: rgb(96, 255, 60);")
        self.label.setObjectName("label")
        self.statuslbl = QtWidgets.QLabel(self.centralwidget)
        self.statuslbl.setGeometry(QtCore.QRect(30, 180, 500, 31))
        self.statuslbl.setStyleSheet("font: 25 15pt \"Bahnschrift Light Condensed\";\n"
                                     "color: rgb(96, 255, 60);")
        self.statuslbl.setText("")
        self.statuslbl.setObjectName("statuslbl")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " "))
        self.label.setText(_translate("MainWindow", "pyTunes"))
        self.statuslbl.setText(_translate("MainWindow", "Press the button to begin.."))
def uifunc(cc):
    app = QtWidgets.QApplication([])
    tm = QtCore.QTimer()
    win = Ui_MainWindow(cc, tm)
    win.show()
    tm.start(1000)
    app.exec()